### ISSUE TITLE
The circled question mark button does not have a tooltip and does not do anything when it is clicked

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [raymak/vpn-recommendation-shield-study#53]
[Affected versions]:
- Nightly 64.0a1 Build ID 20181004224156

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- "xpinstall.signatures.required" is set to "false" in about:config.
- "extensions.legacy.enabled" is set to "true" in about:config.
- The VPN Recommendation Shield Study addon is installed on a clean new profile.
- Be in any of the variations other than the "control" branch.

[Steps to reproduce]:
1. Open the browser and trigger the VPN doorhanger.
2. Hover the circled question mark button from the doorhanger.
3. Click the button and observe the behavior.

[Expected result]:
- Step 2: A tooltip is displayed.
- Step 3: You are redirected to a page explaining why the user is seeing the recommendation.

[Actual result]:
- Step 2: No tooltip is displayed.
- Step 3: Nothing happens.

[Notes]:
- On prior experiments with similar recommendations, the redirect would point to https://support.mozilla.org/en-US/kb/extension-recommendations?as=u&utm_source=inproduct and the button would have the "Why am I seeing this" tooltip.
- Attached a screen recording of the issue:
![the circled button does not redirect](https://user-images.githubusercontent.com/18304511/46615626-57ab3f00-cb21-11e8-93e1-1162e38a8364.gif)

**Comment by raymak** [comment]
This should be fixed.

**Comment by SoftVision-CiprianMuresan** [comment]
It looks like this issue was only partially fixed, I verified that the tooltip now appears on all platforms, but it looks like #63 affects the button's redirect. I'll leave this open until #63 is fixed and will verify after that.

**Comment by raymak** [comment]
This should be fixed now.
